version: '3'
services:
  test:
    build: tests/
    networks:
       - overlay
    depends_on:
      - web
  web:
    build: .
    image: "${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"
    networks:
       - overlay
    ports:
     - "3000:3000"

networks:
  overlay:
