apiVersion: apps/v1
kind: Deployment
metadata:
  name: date-api-green
  labels:
    version: "1.1"
spec:
  selector:
    matchLabels:
      name: date-api-green
  replicas: 3
  template:
    metadata:
      labels:
        name: date-api-green
    spec:
      containers:
        - name: date-api
          image: 439000603071.dkr.ecr.us-east-2.amazonaws.com/date-api:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
