apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: date-api-green
  labels:
    version: "1.1"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: date-api-green
    spec:
      containers: 
        - name: date-api
          image: sleyva97/date-api:1.1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000