apiVersion: v1
kind: Service
metadata:
  name: date-api
  labels: 
    name: date-api
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: http
  selector: 
    name: date-api-blue
